# Generated by Django 4.1.2 on 2023-07-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bclinic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='Demo',
        ),
    ]
